{% set name = "azure-purview-workflow" %}
{% set version = "1.0.0b2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/azure-purview-workflow-{{ version }}.tar.gz
  sha256: 4ae589ee33ba310662d6d88568c352e732b1fc404bda2aff93a5688e67f79c56

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - isodate <1.0.0,>=0.6.1
    - azure-core <2.0.0,>=1.24.0
    - typing-extensions >=4.3.0

test:
  imports:
    - azure.purview.workflow
    - azure.purview.workflow._operations
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Azure/azure-sdk-for-python/tree/main/sdk
  summary: Microsoft Azure Purview Workflow Service Client Library for Python
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - redur
